server:
  port: 8080
eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: '*'
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: ms-vehiculos
          uri: lb://ms-vehiculos:8090
          predicates:
            - Path=/vehiculos/**
        - id: ms-reparaciones
          uri: lb://ms-reparaciones:8091
          predicates:
            - Path=/reparaciones/**
        - id: ms-registro
          uri: lb://ms-registro:8092
          predicates:
            - Path=/registro/**
        - id: ms-reportes
          uri: lb://ms-reportes:8093
          predicates:
            - Path=/reportes/**