server:
  port: 8092
spring:
  datasource:
    url: jdbc:mysql://localhost:3308/registrodb
    username: root
    password: Chile&2023
eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka